This is makeindex, version 2.16 [MiKTeX 22.1].
Scanning style file ./Rapport.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Rapport.acn....done (9 entries accepted, 0 rejected).
Sorting entries....done (31 comparisons).
Generating output file Rapport.acr....done (11 lines written, 0 warnings).
Output written in Rapport.acr.
Transcript written in Rapport.alg.
